use_frameworks!

platform :ios, '10.0'

target 'SFFoundationKit_Example' do
  pod 'SFFoundationKit', :path => '../'

  target 'SFFoundationKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
